import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
      <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
      <p style={{ fontSize: "18px", marginBottom: "30px" }}>
        This project was generated By{" "}
        <a href="https://www.dhiwise.com" style={{ color: "#87CEFA", textDecoration: "none" }}>
          Dhiwise
        </a>
        . Quickly use below links to navigate through all pages.
      </p>
      <ul style={{ listStyle: "none", padding: "0" }}>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/careerspage" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Careerspage
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/contactform" style={{ color: "#87CEFA", textDecoration: "none" }}>
            ContactForm
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/banner2home" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Banner2home
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/aboutus" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Aboutus
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/allsolutionspage" style={{ color: "#87CEFA", textDecoration: "none" }}>
            AllSolutionsPage
          </Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
